### ISSUE TITLE
Getting unresolved dependencies error

### ISSUE THREAD

**Issue by aberba** [TodNaz/Foxid#1]
Shows up when I run `dub` to build the project

```sh
Unresolvable dependencies to package derelict-util:
  derelict-gl3 1.0.24 depends on derelict-util >=1.0.3
  derelict-sdl2 2.1.4 depends on derelict-util ~>2.0.4
```

```d
import foxid;

int main(string[] args)
{
	Game game = new Game(640, 480, "Hello, World!");
	render.background = Color("#FFFFFF");

	game.handle();
	return 0;
}
```

**Comment by TodNaz** [comment]
> Shows up when I run `dub` to build the project
> 
> ```shell
> Unresolvable dependencies to package derelict-util:
>   derelict-gl3 1.0.24 depends on derelict-util >=1.0.3
>   derelict-sdl2 2.1.4 depends on derelict-util ~>2.0.4
> ```
> 
> ```d
> import foxid;
> 
> int main(string[] args)
> {
> 	Game game = new Game(640, 480, "Hello, World!");
> 	render.background = Color("#FFFFFF");
> 
> 	game.handle();
> 	return 0;
> }
> ```

Yes, I should have been careful when posting. It seems to be fixed, please check. Thank!

**Comment by aberba** [comment]
Ok. Checking again

**Comment by aberba** [comment]
Works now. I like how the API is simple. Curious to see how the event Loop will be designed.

Also why `game.handle()` and not `game.run()`?

**Comment by TodNaz** [comment]
> Works now. I like how the API is simple. Curious to see how the event Loop will be designed.
> 
> Also why `game.handle()` and not `game.run()`?

Good afternoon!

I don’t know, it happened. I can make a synonym for "handle" (_alias run = handle), if that is more convenient.

Notice the problems - contact!
All the best to you!

**Comment by aberba** [comment]
Yes `run()` is more obvious.

**Comment by aberba** [comment]
Also I noticed you mix difference of API naming styles in the code...  `event_destroy()` instead of `eventDestroy()`

**Comment by TodNaz** [comment]
Got you. Thanks, I am changing it.
