### ISSUE TITLE
One sound at a time

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#10]
I noticed that if one sound is playing, and while it's playing, another sound is started, the first sound stops before it's finished!

**Comment by TodNaz** [comment]
Yes, while the sounds are poorly implemented, sorry. Use a mixer from sdl.

**Comment by TodNaz** [comment]
Damn, I didn't even think about it, in the next commit I will correct this matter. Thank.

**Comment by TodNaz** [comment]
v0.2.2 seems to have fixed the problem.
