### ISSUE TITLE
Instances order

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#11]
I'm not sure if my program is going to work, but maybe it would with sorting the objects. Like if one rock is above another and you make a gap underneath, depending on the order, the top rock will fall with the bottom one, or there will be a gap between them. Got any ideas? I think I'll try a new way, more like my original game - don't have all the rocks testing for falling, (like when you move it check above for a rock, rather than all the rocks checking for fall every all the time).

**Comment by joelcnz** [comment]
I think the way I mentioned will suffice.

**Comment by TodNaz** [comment]
I don’t know ... In any case, you will have to constantly check for emptiness in the stone below. your idea is tantamount, the stone will still check for the stone higher, which the previous stone will also do. In terms of performance, these ideas do not differ much, but maybe your idea is less productive, well, I think so ... I think it will be easier to check for emptiness at the bottom, it will be much easier in the implementation of the game logic, and not bother with performance .. . At least, I do not know how to implement your idea ... If you are reading nonsense, then I did not understand you ... Sorry, if that)

**Comment by joelcnz** [comment]
It's not working out. Having all the stones and diamonds live (aways checking under each), has problems of sequence more. The way I'm using has problems like duplicating rocks, pushing a rock across only falling when I let the move button go.

Maybe go back to the stones checking (all live stones), but order the Instance arrays so that it checks the player and baddy first then the rocks, also order the rocks with the rocks at the top of the map to be checked first and then each down farther. I don't know how to be reordering the array though.

**Comment by TodNaz** [comment]
I suggest sorting by the height of the objects. The lower, the higher the priority of the object step. Here is an example of sorting: Take all objects, find all falling objects and put them into an array, later, using the standard library std.algorithm, namely, sort the objects using sort, and in the scene, implement in a step the function of their falling, based on the sorted array ... Here's some sample code:
```D
import std.algorithm;
Instance[] fallObjs;
getList().each!((ref obj) {
    if(obj.name == "rock" || obj.name == "diamond") {
        fallObjs ~= e;
    }
});

fallObjs.sort!((a,b) => a.position.y > b.position.y);
```

**Comment by joelcnz** [comment]
Would have to sort the player and baddy too. And I think the higher, the higher priority.

**Comment by TodNaz** [comment]
Yes, that is right. They are all the same type, so it won't be difficult to sort.

**Comment by joelcnz** [comment]
I can't get the sorting to work.

**Comment by TodNaz** [comment]
Sort by hand.

**Comment by joelcnz** [comment]
What do you mean, sort by hand? I can't seem to anything with the Instances array, other than add and remove.

**Comment by TodNaz** [comment]
Write a sort function if sorting in the standard library throws errors. For example:
```D
Instance[] sort(Instance[] objs) @safe
{
    // Sort by height dependencies using usual sorting algorithms from bottom to top.
}
```

**Comment by joelcnz** [comment]
Can you give me and example with the standard sort? Making my own sort is even harder for me.

**Comment by TodNaz** [comment]
You could just look at the sorting algorithm, and find something similar:
```D
public void sort(T)(ref T[] data,bool delegate(T a,T b) @safe func) @trusted
{
	T tmp;
	for(size_t i = 0; i < data.length; i++)
	{
		for(size_t j = (data.length-1); j >= (i + 1); j--)
		{
	    	//if(data[j] < data[j-1]) {
	    	if(func(data[j],data[j-1])) {
	        	tmp = data[j];
	        	data[j] = data[j-1];
	        	data[j-1] = tmp;
	      	}
	    }
	}
}
```
And then you can sort all objects:
```D
ins.sort((Instance a,Instance b) => a.position.y > b.position.y);
```

**Comment by joelcnz** [comment]
Doesn't seem to be making any difference?!
```d
			auto a = getList().dup;
			ssort!(Instance)(ints, (a, b) => a.position.y > b.position.y);
			assert(a == getList());
```

**Comment by TodNaz** [comment]
```D
auto ints = getList().dup;
ssort(ints, (Instance a, Instance b) => a.position.y > b.position.y);
assert(ints == getList());
```

**Comment by joelcnz** [comment]
It's not updating the main instance array.

**Comment by TodNaz** [comment]
I don't know, I checked it myself - it works, here is the proof:
```D
public void sort(T)(ref T[] data,bool delegate(T a,T b) @safe func) @trusted
{
	T tmp;
	for(size_t i = 0; i < data.length; i++)
	{
		for(size_t j = (data.length-1); j >= (i + 1); j--)
		{
	    	//if(data[j] < data[j-1]) {
	    	if(func(data[j],data[j-1])) {
	        	tmp = data[j];
	        	data[j] = data[j-1];
	        	data[j-1] = tmp;
	      	}
	    }
	}
}

public final class Test : Scene
{
	this() @trusted
	{
		import std.stdio;
		import std.random;
		import std.algorithm : each;

		Instance[] ints;
		foreach(_; 0 .. 15) {
			Instance ins = new Instance();
			ins.position = Vec(uniform(0,128),uniform(0,128));
			ints ~= ins;
		}

		ints.each!((ref e) => e.position.write(",")); writeln("\n");
		ints.sort((Instance a,Instance b) => a.position.y > b.position.y);
		ints.each!((ref e) => e.position.write(",")); writeln("\n");
		sceneManager.gameExit();
	}
}
```
![proof](https://imgur.com/TmMHWZt.png)

**Comment by joelcnz** [comment]
I mean that it's not effecting the rest of the usage of instances, it's seperate.

```d
// I'm thinking something like
setList(ints);
```

**Comment by TodNaz** [comment]
This action is possible only inside the scene:
```D
instances = ints;
this.sort(); /// Be sure to sort by depth.
```

**Comment by TodNaz** [comment]
Something like:
```D
ints.each!((ref e) {
    iDestroy_noGC(e);
});

ints.each!((ref e) => add(e));
```

**Comment by joelcnz** [comment]
Ok, that's working better. Though, I'm not sure my game is going to fly, still.

**Comment by joelcnz** [comment]
I can keep the rocks and diamonds in order, but I want the player and bady first or last in line.

**Comment by TodNaz** [comment]
What prevents you from manually adding a player to the last or first place? Just add to the array before all objects, like this:
```D
Instance ins = getInstanceByName("player");
iDestroy_noGC(ins); // Removes without destroying an object from memory.
Instance[] list = getList();
list.sort(...);
list.each!((ref e) {
    iDestroy_noGC(e);
});

add(ins);
list.each!((ref e) => add(e));
```
