### ISSUE TITLE
Not using the game.d loop

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#13]
I want to have my own loops.  Would I be able to use 'Display graph' 'with it's drawing functions, without using the game.d loop? How would I go about it?

I've duplicated my SDL layer (jecsdl -> jecfoxid), and have started merging it with Foxid.

https://github.com/joelcnz/jecfoxid

My part has sprite alphabet and other keyboard characters, (read it off png files). They wrap around, but there's no scroll bar. I've also got a terminal and a basic GUI.

**Comment by TodNaz** [comment]
Hello, joelcnz!
Yes, this is possible, but you will lose all the charm of OOP in the framework, and to return it, you will have to manually process all manager requests in your loop. For example, if you only need to display graphics, you can plot in the following way:
```D
sdlInit(); // Initialize sdl 2.
Window myWindow = new Window();
myWindow.init("MyWindowCaption!",640,480);
myWindow.background = Clr.white;
Display graph = new Display(myWindow); // We create and tell the display that we are drawing into this window.
Event event;
bool isGame = true;
while(isGame) {
    FPS.start();
    while(event.update) {
       if(event.isQuit) isGame = false;
    }

    graph.clear(); // Clear screen
    graph.drawRect(Vec(32,32),Vec(64,64),Clr.red,true); // Drawning rectangle
    graph.drawning(); // Swap buffers

    FPS.rate();
}
```

If you want to use managers, just instantiate them manually, and process them according to the code in this file: [0.2.3/foxid.core.game](https://github.com/TodNaz/Foxid/blob/b72c792abc97669bdef10f8b24dbceef969c83ee/source/foxid/core/game.d)

More questions?

**Comment by TodNaz** [comment]
I understand you are trying to make a GUI. Why is it impossible to issue in the form of copies? Or do you lack the power of the framework?

**Comment by joelcnz** [comment]
Yes, that is more like what I've been thinking.

I have done some work on my own GUI, and use it a bit. I've actually made a platform games that doesn't work any more since I got a new macOS, it was using DSFML - also there were other problems with that library (it's much faster graphics than SDL and Allegro, though).

**Comment by TodNaz** [comment]
Well, in a framework, all objects that have behavior are instances. Make a widget interface that has some parameters for such an element (height, width, etc.), and create an object that inherits both the instance and the widget. In the instance, use events to implement the behavior of such elements, and implement the widget interface. If you want these elements to be able to work in other threads, try to implement the behavior in the `step` event, because it is he who works in a separate thread (if, of course, you allowed the framework to work in multiple threads). You can find an example in the foxid.gui module. More questions?

**Comment by joelcnz** [comment]
I can't seem to get text to draw on the screen, just crashes with 11. Can you give me an example?

**Comment by TodNaz** [comment]
How do you risk it? What is the debugger showing, or did you get an exception? More precisely.

**Comment by TodNaz** [comment]
Example: https://todnaz.github.io/foxid.github.io/foxid/core/display/Display.drawText.html

**Comment by joelcnz** [comment]
I think it has to do with the 'font' part. You example link doesn't help me - can you do an example using your first code in this issue?

**Comment by TodNaz** [comment]
```D
Font f = new Font();
f.load(path,size); // without using the resource manager
f = loader.loadFont(path, size); // Using the resource manager
...
graph.drawText!string("Example", f, Clr.red, Vec(32, 32));
```

**Comment by joelcnz** [comment]
I don't know if I can use a debugger.

**Comment by TodNaz** [comment]
What operating system do you have?

**Comment by joelcnz** [comment]
macOS 64  bit only.

**Comment by TodNaz** [comment]
Download the program "gdb" (GNU Debugger), run the binary through the terminal like this:

`$ gdb ./my-prg`

Later, when it starts, type `run` and give me whatever it prints to the screen

**Comment by joelcnz** [comment]
I don't know what to do here:

Reading symbols from ./bin/jecfoxidtest...

warning: can't find symbol '_D5foxid6physic12__ModuleInfoZ' in minsymtab
(gdb) run
Starting program: /Users/joelchristensen/jpro/dpro2/Testing/JecFoxidTest/bin/jecfoxidtest 
Note: this version of macOS has System Integrity Protection.
Because `startup-with-shell' is enabled, gdb has worked around this by
caching a copy of your shell.  The shell used by "run" is now:
    /Users/joelchristensen/Library/Caches/gdb/bin/zsh
Unable to find Mach task port for process-id 11091: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
(gdb)

**Comment by joelcnz** [comment]
Load image crashes too. (something not initiated?!) Loading stuff from disc not working.

**Comment by TodNaz** [comment]
I still didn't understand what they wanted. Show me the code what and how you did for this.

> Load image crashes too. (something not initiated?!) Loading stuff from disc not working.
How do you download? Through the resource manager? If so, create them like in game.d, otherwise show your code. I don't understand how this can happen.

**Comment by joelcnz** [comment]
```d
// a function JecFoxidLib
bool jf_setup(in string title = "Jec Foxid", int windowWidth = 640, int windowHeight = 480, Color clearColour = Color(0,0,0)) @trusted {
	sdlInit(); // Initialize sdl 2.
	_foxloader = new Loader();
	_foxscene = new SceneManager();
	//_listener = new Listener();
	gWin = new Window();
	gWin.init(title,windowWidth,windowHeight);
	gWin.background = clearColour; //Clr.black;
	gGraph = new Display(gWin); // We create and tell the display that we are drawing into this window.
	assert(jf_initKeys, "keys failure");
	gFont = new Font();
	gFont.load("fonts/DejaVuSans.ttf",gFontSize);
	//gFont = loader.loadFont("fonts/DejaVuSans.ttf",gFontSize);

	return true;
}

// ...

//Test program
void main(string[] args) {
	assert(jf_setup("JecFoxid Test",640,480, Color(128,128,128)), "jf setup failed");
	Vec pos;

	//auto jrect = JRectangle(Vec(50,100), Vec(32,32), Clr.blue, BoxStyle.solid);
	SDL_Rect rect = SDL_Rect(50,100,32,32);
	auto jrect = JRectangle(rect, BoxStyle.solid, SDL_Color(0,0,255));
	auto jrectOl = JRectangle(rect, BoxStyle.outLine, SDL_Color(255,255,255));

	//Image[] sprites = loader.load!ImageSurface("assets/RockDashColoured.png").image.strip(Vec(0,0), 24, 24);

	//auto jxt = JText("Hello JecFoxid","fonts/DejaVuSans.ttf",12);
	//auto jxt = JText("Hello JecFoxid",gFont);
	//jxt.position = Vec(20,50);
	auto font = new Font();
	assert(font, "font fail");
	font.load("fonts/DejaVuSans.ttf",12);

	int stepSize =  4;

	bool done = false;
	while(! done) {
		FPS.start();
		while(gFEvent.update) {
			if(gFEvent.isQuit) 
				done = true;
		}

		SDL_PumpEvents();		

		bool up    = g_keys[SDL_SCANCODE_UP   ].keyPressed; 
		bool down  = g_keys[SDL_SCANCODE_DOWN ].keyPressed; 
		bool left  = g_keys[SDL_SCANCODE_LEFT ].keyPressed; 
		bool right = g_keys[SDL_SCANCODE_RIGHT].keyPressed; 

		pos.x += left && ! right ? -stepSize : right && ! left ? stepSize : 0;
		pos.y += up   && ! down  ? -stepSize : down  && ! up   ? stepSize : 0;

		//mixin(jm_trace("up down left right".split));

		gGraph.clear(); // Clear screen
		gGraph.drawRect(pos,pos + Vec(32,32),Clr.red,true); // Drawning rectangle
		jrect.draw(gGraph);
		jrectOl.draw(gGraph);
		//jxt.draw(gGraph);
		gGraph.drawText("This is\na test",font,Clr.white,Vec(50,30));
		//gGraph.drawArc(Vec(200,30), 15,[Angle(0.5),Angle(0.8)], Clr.orange); // Error: no property drawArcFill for type foxid.core.display.Display
		gGraph.drawCircle(Vec(200,30),15,Clr.green, true);
		gGraph.drawCircle(Vec(200,30),15,Clr.white, false);
		gGraph.drawning(); // Swap buffers

		FPS.rate();
	}
}
```

**Comment by TodNaz** [comment]
I understood what the problem is. You are creating a non-main window. Create a window in _window so the fonts can access the main render. If anything, I'll fix it later and add an implicit redirect to another renderer being created.

**Comment by TodNaz** [comment]
Example:
```D
_window = new Window();
_window.create(w,h,c); /// v0.3.0
_window.init(c,w,h); /// >v0.3.0
```

**Comment by joelcnz** [comment]
Yay! It's working!
