### ISSUE TITLE
drawing primetives not found

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#14]
gGraph.drawArcFill(Vec(200,30), 15,[Angle(0.5),Angle(0.8)], Clr.orange); // Error: no property drawArcFill for type foxid.core.display.Display
gGraph.drawArc .. - same  (no property  ..)

gGraph.drawRect .. - works in the same scope.

**Comment by TodNaz** [comment]
This feature appeared only in version 3.0.
