### ISSUE TITLE
Error with loading strip

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#15]
version: 0.3.0
g_spriteList = loader.load!ImageSurface("assets/RockDashColoured.png").image.strip(Vec(0,0), 24, 24);

Now says: 
```
Error: no property image for type foxid.type.image.ImageSurface
```
What do I put now?

**Comment by TodNaz** [comment]
Yes, sorry, I copied from scratch. Use ʻimageHandle`, or refer to it as if it were a picture. Sorry again for the name change.
[Here](https://todnaz.github.io/foxid.github.io/foxid--foxid.type.image.html#.ImageSurface.imageHandle)
