### ISSUE TITLE
strip start position wrong

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#2]
I've got a png file with a strip of sprites. The sprites are 24x24. To choose the 6th sprite, I put:

```d
dirsDasher.strip("assets/rockdash5.png", Vec(5 * 24,0), 24,24);
```

But get the wrong sprite?!
![rockdash5](https://user-images.githubusercontent.com/653293/91649770-8642b200-eacb-11ea-9f4c-da04a69845db.png)

I get this one:
<img width="51" alt="Screen Shot 2020-08-30 at 2 18 06 PM" src="https://user-images.githubusercontent.com/653293/91649777-a5d9da80-eacb-11ea-8811-fc0fe4b034de.png">

**Comment by TodNaz** [comment]
Try to get the sprite like this:
```D
loader.load!ImageSurface("assets/rockdash5.png").strip(Vec(0,0), 24,24)
			.get(5);
```
More details: https://todnaz.github.io/foxid.github.io/foxid/type/image/Image.strip.html
(You can get the sprite with the get (index) command)

**Comment by joelcnz** [comment]
I still can't get it to work. I've looked at your link, and the Animation API.

```d
        Animation dirsDasher = new Animation();
        //dirsDasher.load!ImageSurface("assets/rockdash5.png").strip(Vec(0,0), 24,24).get(5);
        dirsDasher.strip("assets/rockdash5.png", Vec(0,0), 24, 24); //.get(5);
```

**Comment by TodNaz** [comment]
Well, since you want to do with animation, I suggest:
```D
Animation dirsDasher = new Animation();
//dirsDasher.load!ImageSurface("assets/rockdash5.png").strip(Vec(0,0), 24,24).get(5);
dirsDasher.strip("assets/rockdash5.png", Vec(0,0), 24, 24); //.get(5);
Image frame = dirsDasher.frames.get(5);
```

**Comment by joelcnz** [comment]
But now what do I do with 'frame',  how do I make it part of the animation?

```d
ofsprite.animation = dirsDasher;
```

**Comment by TodNaz** [comment]
I take it you want to capture a piece? Maybe this will help:
```D
import foxid.utils.array;
dirsDasher.frames = List!Image(dirsDasher.frames.get(IndexIn(5,to)));
/// or
dirsDasher.frames = List!Image(dirsDasher.frames.array[5 .. to]);
ofsprite.animation = dirsDasher;
```
But in general, I would recommend keeping the direction of the character like this:
```D
Image[] cadrs = loader.load!ImageSurface("assets/rockdash5.png").strip(...).array;

Image dasherUp = cadrs[7];
Image dasherDown = cadrs[5];
Image dasherLeft = cadrs[6];
Image dasherRight = cadrs[8];
```
And later, when it moves, use:
```D
if (napr == left) {
	ofsprite.image = dasherLeft;
}
if (napr == right) {
	ofsprite.image = dasherRight;
}
```

**Comment by joelcnz** [comment]
I get - Error: no property strip for type foxid.type.image.ImageSurface. With:
```d
Image[] cadrs = loader.load!ImageSurface("assets/rockdash5.png").strip(Vec(0,0), 24, 24).array;
```

**Comment by TodNaz** [comment]
`Image[] cadrs = loader.load!ImageSurface("assets/rockdash5.png").image.strip(Vec(0,0), 24, 24).array;`. (Good night.)

**Comment by joelcnz** [comment]
Now it won't display the sprite, and I've  tried 'visible = true;', 'withDraw = true;' and 'ofsprite.visible = true;'

```d
final class Dasher : Instance {

    this() @trusted {
        name = "Dasher";

        Image[] cadrs = loader.load!ImageSurface("assets/rockdash5.png").image.strip(Vec(0,0), 24, 24).array;

        ofsprite.image = cadrs[5];
        visible = true;

        position = Vec(5 * g_stepSize, 5 * g_stepSize);
    }
```

**Comment by TodNaz** [comment]
Maybe you didn't add it to the scene?
```D
class MyScene : Scene {
    this() @safe {
        add(new Dasher());
    }
}
```

**Comment by joelcnz** [comment]
I think I do, I had it display with animation settings.

https://github.com/joelcnz/RockDash

**Comment by TodNaz** [comment]
Check if the frame has loaded, or try:

**Comment by TodNaz** [comment]
Check if the frame has loaded, or try:
```D
assert(cadr[5].isNull);
//or
foreach(ref e; cadrs) {
    e.make();
}
```

**Comment by joelcnz** [comment]
The following worked. Thanks.

```d
foreach(ref e; cadrs) {
    e.make();
}
```
