### ISSUE TITLE
Can you get my game working?

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#22]
You try my game if you want. You might just use 'dub -- GameLearn 1 Joel', put your name instead of mine at the end. There are other lots of levels, but I think they're too hard (I just converted levels from ages ago).

Let me know if you have any trouble.

[1] https://github.com/joelcnz/RockDash

**Comment by TodNaz** [comment]
I cannot compile your project. Apparently, your dependencies are missing functions:
```
source/app.d(538,21): Error: undefined identifier jm_upDateStatus
source/app.d(189,24): Error: template instance source.app.upDate!string error instantiating
source/app.d(196,9): Error: undefined identifier tce
source/app.d(538,21): Error: undefined identifier jm_upDateStatus
source/app.d(224,9): Error: template instance source.app.upDate!(string, string, string, string, string) error instantiating
source/app.d(538,21): Error: undefined identifier jm_upDateStatus
source/app.d(506,9): Error: template instance source.app.upDate!(string, string, string) error instantiating
source/app.d(515,10): Error: undefined identifier tce
source/app.d(516,9): Error: undefined identifier tce
source/io/load.d(25,5): Error: undefined identifier jm_backUp
```

**Comment by joelcnz** [comment]
Use the zip file (it has 'jmisc' library, and another one).

**Comment by TodNaz** [comment]
Yes, I played your game. Cool. But I noticed: the memory flows when the level is restarted. Are you re-creating in-game exempts? Are you loading resources manually again? Reconsider reloading the level. So far, I have not observed any errors.

**Comment by joelcnz** [comment]
I haven't worked on it for a while, (I've been working on a playform game). I'll have to check out the memory situation. I try to clear the Instance objects, but some things don't quite resert, I don't know if the multi threading mucks things up.

**Comment by TodNaz** [comment]
Multithreading will only mess up non-asynchronous memory reads, if any. You can reload the game with the `gameRestart` event and clean up the instances there. And if you want the resources, for example, animation, not to be cleaned, you can add it to the resource loader so that you do not load it again later, checking if it is in the resources, for example:
```D
class AnimateFrames : Resource
{
    Animation anim;
    string name;
    string path;

    this() @safe
    {
        anim = new Animation();
    }

    override void load(string path,string name) @safe { anim.strip(path,...); this.name = name; }
    override string getName() @safe nothrow { return this.name; }
    override string getPath() @safe nothrow { return this.path; }
    override void free() @trusted { anim.free(); }
}

...

sprite.animation = loader.load!AnimateFrames("frames.png","MyName");
```
This, of course, is a crutch, but the resources will not be loaded again when the level is restarted, and will be controlled by the manager.
