### ISSUE TITLE
Resizing images

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#23]
How do I resize loaded image files?

```d
auto getResize(Image src,int newWidth,int newHeight) {
		auto newImg = new Image();

		window.blendMode = BlendMode.blend;
		newImg.createTexture(newWidth,newHeight,Color(0,0,0,255));
		window.blendMode = BlendMode.none;

		try {
			src.blit(newImg,Vec(0,0), newWidth,newHeight);
		} catch(ImageException e) {
			writeln(e);
			assert(0);
		}

		return newImg;
	}

// ...

		goodyGfx = new Sprite();
		foxloader.load!Image("gfx/g.png", "goodyGfx");
		goodyGfx.image = foxloader.get!Image("goodyGfx");
		goodyGfx.image = getResize(goodyGfx.image,cellWidth,cellHeight);

```

I get this error: foxid.core.exception.ImageException@../../../../.dub/packages/foxid-master/foxid/source/foxid/core/exception.d(100): There is no surface in the current picture.

Also, draw filled rectangle only works if the second Vec is to the right and below. Unfilled rectangle works still in that scenario. I was wondering why the outline one worked but the filled one didn't show anything.

**Comment by TodNaz** [comment]
`blit` is only effective when the original image is a surface and the attached image is also a surface. Do with the edit function:
```D
src.edit((graph) {
    Sprite conf  = new Sprite();
    conf.image = image;
    conf.width = newWidth;
    conf.height = newHeight;
    conf.position = Vec(0,0);

    graph.draw(conf);
});
```

And if you just need to resize, resize through the sprite, using its `width`,` height` properties. Sprite is a flexible image rendering solution. 
---
[1]: https://todnaz.github.io/foxid.github.io/foxid--foxid.type.sprite.html
[2]: https://todnaz.github.io/foxid.github.io/foxid--foxid.type.image.html

**Comment by joelcnz** [comment]
I don't see how your example works - src seems ignored.

Though, with you saying to use width and height, in regards to using Sprite, I got that working.

**Comment by TodNaz** [comment]
Those. you either load it as a surface and edit it in surface mode with the `blit` functions, or set image parameters in rendering using the` Sprite` class.

**Comment by joelcnz** [comment]
Can you give me an example of using ```blit```?

**Comment by TodNaz** [comment]
```D
auto img = loader.load!ImageSurface("...");
img.blit(otherImage,Vec(32,32),widthOtherImage,heightOtherImage);
img.fromTexture();
```

https://todnaz.github.io/foxid.github.io/foxid--foxid.type.image.html
