### ISSUE TITLE
Keys not always working

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#24]
Is there any gotchas with reading key presses? SDL_SCANCODE_0 - SDL_SCANCODE_9 don't work in some of my programs.

**Comment by TodNaz** [comment]
There are no scancode tracking in the framework. All keys are tracked through event.getKeyDown / event.getKeyUp.
For example, this example works:
```D
override void event(Event event) @trusted
{
    if(event.getKeyDown == '1')
        writeln("1");
}
```

And why your scancodes do not work - look already in the SDL wiki, if you initialize its functions yourself.

**Comment by joelcnz** [comment]
I tried your event system, but its use doesn't cover what tried to explain to you before.

Anyway, I got the number keys to work a program I was working on.
