### ISSUE TITLE
Tiles

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#5]
Know a good way to go about doing tiled screens?

This is how I've been trying: https://github.com/joelcnz/RockDash

**Comment by TodNaz** [comment]
```D
// in scene:
add(Tile(Image,Vec,depth));
```
Only they will never be drawn over sprites / objects.

**Comment by joelcnz** [comment]
I think so.

**Comment by TodNaz** [comment]
Well, I compiled your project, and it seems to work as it should. Or did you mean something else by that? [![https://imgur.com/3Zer7yI.png](https://imgur.com/3Zer7yI.png)](https://imgur.com/3Zer7yI.png)

**Comment by joelcnz** [comment]
I just think my way might not be very good. Like there's the two dimensional array that would be faster, than having to cycle through all the tiles each time to check for a brick or some thing.

**Comment by TodNaz** [comment]
Well, you can make a grid array and check against it, that will be faster:
```D
void check(Vec checkPos) @safe {
    return arr[checkPos.intX/24][checkPos.intY/24] == 'm';
}
```
Well, or you can check for availability with [getInstanceByMask](https://todnaz.github.io/foxid.github.io/foxid/core/scene/Scene.getInstanceByMask.html) through [shape](https://todnaz.github.io/foxid.github.io/foxid/type/shape.html):
```D
if(getInstanceByMask(hero.position + checkPos,ShapeRectangle(0,0,32,32)).name == "brick") {
    ...
}
```

**Comment by joelcnz** [comment]
Trying 'getInstanceByMask', is moving correctly some places, and not moving in other places where it should.

**Comment by TodNaz** [comment]
You have the wrong mask for objects:
```D
shape = ShapeRectangle(pos, pos + Vec(g_stepSize, g_stepSize));
```

The contact mask should not depend on the position, it should be clearly defined:
```D
shape = ShapeRectangle(Vec(0,0),Vec(g_stepSize,g_stepSize));
```

**Comment by TodNaz** [comment]
In addition, I note that when you search for an instance by mask, there is a chance that it will not find the object, so try to check this:
```D
auto obj = getInstanceByMask(...);
if(obj !is null) ...
```

**Comment by joelcnz** [comment]
Thanks, it's working.
