### ISSUE TITLE
Speed and key pressing

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#6]
With key pressing, I want the dasher to move and keep moving, not: move once, sit for a short time, then race across.

To compile my program you'll need my J Misc code (https://github.com/joelcnz/JMiscLib). (has 'mixin(trace("diamonds score".split));' to show the variable name and value).

**Comment by TodNaz** [comment]
```D
final class Dasher : Instance {

    Image dasherUp;
    Image dasherDown;
    Image dasherLeft;
    Image dasherRight;

    int score,
        diamonds;

    int index = -1;

    struct Dirs {
            Vec dir;
        }

    auto dirs = [Dirs(Vec(0,-g_stepSize)), Dirs(Vec(g_stepSize,0)), Dirs(Vec(0,g_stepSize)), Dirs(Vec(-g_stepSize,0))];

    this() @trusted {
        name = "dasher";

        dasherUp = g_spriteList[SpriteGraph.up];
        dasherDown = g_spriteList[SpriteGraph.down];
        dasherLeft = g_spriteList[SpriteGraph.left];
        dasherRight = g_spriteList[SpriteGraph.right];

        ofsprite.image = dasherUp;

        position = Vec(6 * g_stepSize, 5 * g_stepSize);
    }

    override void step() @safe {
        if (index != -1) {
            auto obj = sceneManager.current.getInstanceByMask(position + dirs[index].dir, ShapeRectangle(Vec(1,1), Vec(g_stepSize - 1,g_stepSize - 1)));

            if (obj !is null) {
                import std.algorithm : canFind;
                import std.string : split;

                switch(obj.name) {
                    default: break;
                    case "gap", "mud", "diamond", "aswitch":
                        position += dirs[index].dir;
                        switch(obj.name) {
                            default: break;
                            case "gap":
                                // into a gap sound
                            break;
                            case "mud":
                                // clear mud sound
                            break;
                            case "diamond":
                                // sound for picking up
                                score += 10;
                                diamonds += 1;
                                mixin(trace("score diamonds".split));
                            break;
                            case "aswitch":
                                import std.stdio; writeln("Switch triggered");
                            break;
                        }
                    break;
                }
                if ("mud diamond aswitch".split.canFind(obj.name)) {
                    obj.destroy();
                    sceneManager.current.add(new Piece(obj.position, g_chars[SpriteGraph.gap]));
                }
            } // obj not is null
        }
    }

    override void event(Event event) @safe {
        //int index = -1; // 0 - up, 1 - right, 2 - down, 3 - left

        switch(event.getKeyDown) {
            default: break;
            case Key.up:
                ofsprite.image = dasherUp;
                index = 0;
            break;
            case Key.right:
                ofsprite.image = dasherRight;
                index = 1;
            break;
            case Key.down:
                ofsprite.image = dasherDown;
                index = 2;
            break;
            case Key.left:
                ofsprite.image = dasherLeft;
                index = 3;
            break;
        }
    }
}
```
Maybe you wanted this?

**Comment by joelcnz** [comment]
That makes it keep going and fixing that it goes back to how it was, but using a step method, (better coded I think).

I was like: while key down move.

**Comment by TodNaz** [comment]
Well, start the movement timer, and move it to the gap, for example, half a second:
```D
if((MonoTime.currTime - timer).total!"msecs" > 500) {
   move();
}
```

**Comment by joelcnz** [comment]
It's not the timing. Like moving along, you hold the key down for a second, it moves a long for a second. Not, you hold the key down for a second, it moves once, then maybe then keeps moving at its own rate (I don't want the word processor cursor movement).

**Comment by TodNaz** [comment]
So I suggested that you transfer the motion block to the `step` event, and then it will not stop, because event will be called when a key is pressed or events are triggered. Limit the speed with a timer:
```D
if((MonoTime.currTime - currentTIme).total!"msecs" > 500) {
    movement();
}
```
Do you want the executable to move continuously like this when pressed? This will help you, and will limit your speed and leave movement at 24 cells.

**Comment by joelcnz** [comment]
I want the movement like what you'd use in a platform game. Like you hold down the right key, till you get near the edge, then you tap the jump key, (while still holding down the right key).

As it is, you'd have to tap the right key, wait till you're near the edge and then tap the up key to jump.

**Comment by joelcnz** [comment]
Have a look in 'base.d', it deals with key presses.

https://github.com/joelcnz/JecsdlLib

**Comment by TodNaz** [comment]
> I want the movement like what you'd use in a platform game. Like you hold down the right key, till you get near the edge, then you tap the jump key, (while still holding down the right key).
> 
> As it is, you'd have to tap the right key, wait till you're near the edge and then tap the up key to jump.

I see no problems in implementation. Track keystrokes in the event `event`, and multiple keystrokes can be tracked too, you just have to think, can you imagine?



> Have a look in 'base.d', it deals with key presses.
> 
> https://github.com/joelcnz/JecsdlLib

What is stopping you from making an overlay? The sdl of the `event._sdl_handle` structure can be pulled from the event. From the display too: `window._sdl_render ()`, if that's convenient for you.

**Comment by TodNaz** [comment]
In addition, have I already given you the motion algorithm you needed, or do you need to do it all for you?

**Comment by joelcnz** [comment]
I need more code examples, I don't know what to do with event._sdl_handle and such.

**Comment by TodNaz** [comment]
`event._sdl_handle` passes the` SDL_Event` structure, and you can use it to track events that were not available in foxid. Only the structure is given, not the pointer, so every time you need to take a new structure:
```D
SDL_Event ev = event._sdl_handle();
ifev.type == SDL_UP) ....
```
And this way you can attach your library.

**Comment by joelcnz** [comment]
I might be able to do something with that, thanks.
