### ISSUE TITLE
404 link error

### ISSUE THREAD

**Issue by joelcnz** [TodNaz/Foxid#9]
https://todnaz.github.io/foxid.github.io/foxid/math/func.html

**Comment by TodNaz** [comment]
Strange, there is a file of such a page, but the page does not open ... Later I'll see how to fix it, thanks for noticing!

***

- [ ] Fix opening func.html

**Comment by TodNaz** [comment]
[foxid.math.funcional](https://todnaz.github.io/foxid.github.io/foxid/math/funcional.html) - Fixed by renaming the module.
